### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by steveklabnik**
First commit: extra extern crates that weren't needed

Second commit: basically stylistic fixes

### CODE REVIEW

**Comment by dirvine** [comment]
Welcome and huge thanks for this PR 
This is causing a failure in test ( https://travis-ci.org/dirvine/self_encryption/jobs/57998935#L1268 ) due to a rand call there (only in the test though).

**Comment by steveklabnik** [comment]
Oh! Yeah, I didn't have the prereqs, so I didn't _run_ the tests, but I should be able to fix it...

**Comment by steveklabnik** [comment]
Check that new commit. That's generally the Right Way (tm)

**Comment by dirvine** [comment]
Excellent Steve Thanks for that.

**Pull request merged**
